# Generated by Django 3.0.8 on 2021-02-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
