# Generated by Django 3.0.8 on 2021-02-16 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_favouritesong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likedby',
            field=models.ManyToManyField(related_name='likedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavouriteSong',
        ),
    ]
