# Generated by Django 3.0.8 on 2021-03-21 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20210216_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file',
            new_name='file_name',
        ),
        migrations.AlterField(
            model_name='song',
            name='likedby',
            field=models.ManyToManyField(blank=True, related_name='likedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
