# Generated by Django 3.0.8 on 2021-03-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210321_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
