# Generated by Django 3.0.8 on 2021-04-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
