# Generated by Django 3.0.8 on 2021-04-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile1',
        ),
    ]
